services:
  db:
    image: postgres:17-alpine
    container_name: family-wallet-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - family-wallet-postgres-data:/var/lib/postgresql/data

volumes:
  family-wallet-postgres-data:
    
    